services:
  db:
    image: ghcr.io/baosystems/postgis:15-3.5 # use unofficial image until official image is available
    container_name: footprints_dev_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"