[instance]
server-version = "6.1"

[project]
schema-dir = "shared/dbschema"

[hooks]
schema.update.after = "npx @gel/generate edgeql-js"

[[watch]]
files = ["server/queries/*.edgeql"]
script = "npx @gel/generate queries"